### ISSUE TITLE
Flamegraph not showing on vector despite correct installation 

### ISSUE THREAD

**Issue by sofianinho** [spiermar/vector-pmda#2]
Hello everyone,
Hopefully someone could help.

I (re)installed pcp from the github sources, and added the generic metric and I think the installation worked fine.
The steps are:
- Grab the pcp repo from github (the gerrit one does not work anymore, it is worth updating the vectoross getting started documentation since the source link given is dead).
- configure, make, make install
- Clone this repo inside: /var/lib/pcp/pmdas/generic (this is the location of PMCDCONF pointed out by /etc/pcp/pmcd/pmcd.conf)
- Grab perf-map-agent, make and then move the bin/* to /usr/local/bin
- Grab Vector, set enableFlameGraph to true in index.config.js (you need the workaround in https://github.com/Netflix/vector/issues/170 with node >=8)
- run pminfo -fT generic with a positive result
```
pminfo -fT generic

generic.systack
Help:
The time in seconds since the 1st of January, 1970.
    value 1508951801

generic.jstack
Help:
The time in seconds since the 1st of January, 1970.
    value 1508951801

generic.heatmap
Help:
The time in seconds since the 1st of January, 1970.
    value 1508951801
```
- restart pmcd pmwebd apache2 at the end of the installation. At this point, I am seeing the FlameGraph option in vector
- Once you try and click on the Generate CPU Flame Graph, there is an error:
```
ERROR PMWEBD error, code -12357: Unknown metric name 
```
The pmwebd logs say:
```
[Wed Oct 25 17:02:01] pmwebd(18710): [127.0.0.1:41566] failed to lookup metric vector.task.cpuflamegraph
```
And the generic log says:
```
Log for pmdageneric on PoCRANaaS-1 started Wed Oct 25 18:57:26 2017

/bin/cat: '/var/lib/pcp/pmdas/generic/JSTACK/threaddump*.txt': No such file or directory
ERROR: No stack counts found
Failed to open /tmp/perf-9766.map, continuing without symbols
Failed to open /tmp/perf-6284.map, continuing without symbols
[vdso] with build id 7a29fd6e058e0d42e9e6ed28d7dac177f8401815 not found, continuing without symbols
Failed to open /tmp/perf-6945.map, continuing without symbols
Failed to open /tmp/perf-6470.map, continuing without symbols

Log finished Wed Oct 25 19:04:52 2017
```

The additional weird thing is that there is content inside the /mnt/logs/pcp/generic/SYSTACK/, /mnt/logs/pcp/generic/HEATMAP/ folders
```
$ ll  /mnt/logs/pcp/generic/SYSTACK/
total 30552
drwxr-xr-x 2 root root    4096 oct.  25 19:28 ./
drwxr-xr-x 5 root root    4096 oct.  25 19:26 ../
-rw-r--r-- 1 root root   89794 oct.  25 19:17 perf-cpu-stacks.folded
-rw------- 1 root root 3071080 oct.  25 18:16 perf.data.2017-10-25_18:16:30
-rw------- 1 root root 5813904 oct.  25 18:18 perf.data.2017-10-25_18:17:20
-rw------- 1 root root 4618928 oct.  25 18:19 perf.data.2017-10-25_18:18:22
-rw------- 1 root root 3124528 oct.  25 18:21 perf.data.2017-10-25_18:20:24
-rw------- 1 root root 4653328 oct.  25 18:22 perf.data.2017-10-25_18:21:21
-rw------- 1 root root 4612340 oct.  25 19:04 perf.data.2017-10-25_19:03:12
-rw------- 1 root root 2778684 oct.  25 19:06 perf.data.2017-10-25_19:05:04
-rw------- 1 root root 2494900 oct.  25 19:17 perf.data.2017-10-25_19:16:41

$ ll  /mnt/logs/pcp/generic/HEATMAP/
total 19644
drwxr-xr-x 2 root root    4096 oct.  25 19:18 ./
drwxr-xr-x 5 root root    4096 oct.  25 19:26 ../
-rw------- 1 root root 2940037 oct.  25 18:16 perf.data.20171025-18:16:30
-rw------- 1 root root 6573317 oct.  25 18:19 perf.data.20171025-18:18:22
-rw------- 1 root root 3155541 oct.  25 18:21 perf.data.20171025-18:20:24
-rw------- 1 root root 7432821 oct.  25 19:05 perf.data.20171025-19:03:12
```
The content look like a content from perf, so something you would see with flamegraph, and the timestamps at the end of the filenames correspond to moments I clicked on the Generate... button (not all the moments though, a lot missing). So it seems as if part of the job is done by the generic metric. For more info, it is running on my system 
```
$ ps aux|grep generic
root     24025  0.0  0.0  16452  1124 ?        S    19:26   0:00 /var/lib/pcp/pmdas/generic/pmdageneric -d 400 -l /mnt/logs/pcp/generic/generic.log
```

So guys, what's missing here and why do I have that error ?

Thanks for your help and guidance!

**Comment by sofianinho** [comment]
Hi,
I think I am advancing on the issue a little bit. I noticed the error:
```
Error: Failed requesting vector.task.cpuflamegraph: PMWEBD error, code -12357: Unknown metric name
```
Using the developer tools to see what request the "Generate CPU Flame Graph" button does, I've seen that the metric called was not "generic" actually but: "http://localhost:44323/pmapi/327733311/_store?name=vector.task.cpuflamegraph&value=60" so the metric is: "vector.task.cpuflamegraph", which obviously I don't have on my system.

I replaced "vector.task.cpuflamegraph" by "generic.heatmap" in my browser (url: http://localhost:44323/pmapi/1201442206/_store?name=generic.heatmap&value=60) and got the error
```
PMWEBD error, code -12387: No permission to perform requested operation
```
At least it's something.

I will replace the  "vector.task.cpuflamegraph" by "generic.heatmap" or "generic.systack" (not sure) in the following file of vector: /src/app/components/flamegraph/flamegraph.service.js, before recompiling it, at least to get vector to ask for the right metric, and then I will deal with the "permission" problem separately (maybe it's an apache server user problem, we'll see). 

I Will update the issue in case someone has a similar issue

**Comment by ms4720** [comment]
Are you still having the problem? some things I would do are:
1.  look at /var/lib/pcp/pmns dir and see if the generic file is there and if it has been added to the root file in the same directory
2. reinstall using the pcp.io repo and see if that helps

**Comment by spiermar** [comment]
@sofianinho @ms4720 Can you try with the current `master`?

**Comment by ms4720** [comment]
@spiermar I have flame graphs, including hacky solution to make java work inside of docker, I like all the recent commits though and will take a look.  Any idea when they will show up in debs?

**Comment by spiermar** [comment]
@ms4720 the PMDA?

**Comment by ms4720** [comment]
@spiermar  yes the vector-pmda

**Comment by sofianinho** [comment]
hi @spiermar 
Sorry for not being reactive on this topic, I admit I have to let it by the curb while I focused on something else
I will update as soon as I modify my tested. Thank you for answering (I felt alone here for a little while :) )

**Comment by spiermar** [comment]
@ms4720 I have to check with Nathan (from PCP) to see if it makes sense to include this PMDA at this point. From my point of view, I don't things its stable enough to be shipped with PCP right now, but hopefully I'll get the time this quarter to get it there.

**Comment by spiermar** [comment]
@sofianinho from the error message, you had the same issue as @ms4720 and others. The client code was updated to use a new version of the PMDA (`vector.task.*` instead of `generic.*`), but the PMDA code here was not in sync with our internal version. With the recent sync, it should be working. Please reopen the issue in case you're still having problems.

**Comment by ms4720** [comment]
@spiermar  if I can get it deployed at work I might have some time to help with that
