### ISSUE TITLE
Is vector supposed to be a drop in pmda for pcp?

### ISSUE THREAD

**Issue by ms4720** [spiermar/vector-pmda#5]
the pcp installed webroot, in /etc/pcp/pmwebd/pmwebd.options,  is  `$PCP_SHARE_DIR/webapps` and the default for vector is `$PCP_SHARE_DIR/jsdemos` and there are a number of directories existing under `$PCP_SHARE_DIR/webapps/vector`.  Did I miss something in the docs?

**Comment by spiermar** [comment]
No, it's just a factor of our internal `pmwebd.options` being different from PCP's default. https://github.com/spiermar/vector-pmda/commit/db29b0314607c915342c557f3ab9dfdec85d5137 should fix this.

**Comment by spiermar** [comment]
I should actually update the PMDA to use the `webroot` environment variable.
