### ISSUE TITLE
problem loading server/libjvm.so from cpuflamegraph.sh as root 

### ISSUE THREAD

**Issue by ms4720** [spiermar/vector-pmda#7]
running cpuflamegraph.sh in /var/lib/pcp/pmdas/vector directory I get the following error: 

```[ perf record: Captured and wrote 0.994 MB /var/log/pcp/vector/cpuflamegraph/perf.data.27189 (5880 samples) ]
DEBUG 27189 02:10:32.395: Collecting symbol maps
DEBUG 27189 02:10:33.632: Processing profile
Failed to open /opt/jdk1.8.0_162/jre/lib/amd64/server/libjvm.so, continuing without symbols
DEBUG 27189 02:10:34.238: Flame Graph generation
DEBUG 27189 02:10:34.261: Usage: minflt 2672 cminflt 44312 majflt 0 cmajflt 0 utime 1 stime 0 cutime 158 cstime 22
DEBUG 27189 02:10:34.262: DONE
```

/opt/jdk1.8.0_162/jre/lib/amd64/server/libjvm.so exists and is readable:

```
ls -l /opt/jdk1.8.0_162/jre/lib/amd64/server/libjvm.so
-rwxr-xr-x 1 uucp 143 17043762 Dec 20 05:24 /opt/jdk1.8.0_162/jre/lib/amd64/server/libjvm.so
```

It works if I do it inside docker exec, .so loads and I get my perf-pid.map

**Comment by spiermar** [comment]
@ms4720 exists in the host or inside the docker container?

**Comment by ms4720** [comment]
it exists in the docker container

**Comment by ms4720** [comment]
this fixed the map file generation issue, still not having good svg generated though.  Will send a pull later 

--- a/perfmaplib.sh
+++ b/perfmaplib.sh
@@ -231,7 +231,7 @@ function _container_java_map {
        local gid=$(_pid_to_uid $pid)
        local opts=""
        (( PM_UNINLINED )) && opts="unfoldall"
-       nsenter -t $pid -m -p -u -S $uid -G $gid sh -c '
+       nsenter -t $pid -a  -S $uid -G $gid sh -c '
                cd '$nspma'
                '$java_home'/bin/java -cp attach-main.jar:'$java_home'/lib/tools.jar net.virtualvoid.perf.AttachOnce '$nspid' '$opts' > /dev/null' > /dev/null

**Comment by spiermar** [comment]
When you say a good SVG you mean an SVG with the symbols resolved?

**Comment by ms4720** [comment]
the problem was caused by the lack of a '-r' option to nsenter:
this line: nsenter -t $pid -m -p -u -S $uid -G $gid sh -c '
needed to be this: nsenter -t $pid -m -p -u -r -S $uid -G $gid sh -c ' 

I am not sure what the issue was but that fixed the issue.  

Sorry for the noise on the matter, just starting to use github.
